import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SocialSection from "@/components/Social/Social";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aman Gupta - React Developer",
  description: "Generated by Aman Gupta",
  creator: "Aman Gupta",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Anton&family=Barlow:ital@1&family=Creepster&family=Lato&family=Montserrat&family=Mulish&family=REM&family=Roboto&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
        <SocialSection />
      </body>
    </html>
  );
}
